{{- if .Values.snowflake.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dbt-medallion.fullname" . }}-snowflake
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SNOWFLAKE_ACCOUNT: {{ .Values.snowflake.account | quote }}
  SNOWFLAKE_USER: {{ .Values.snowflake.user | quote }}
  SNOWFLAKE_PASSWORD: {{ .Values.snowflake.password | quote }}
  SNOWFLAKE_ROLE: {{ .Values.snowflake.role | quote }}
  SNOWFLAKE_WAREHOUSE: {{ .Values.snowflake.warehouse | quote }}
  SNOWFLAKE_DATABASE: {{ .Values.snowflake.database | quote }}
  SNOWFLAKE_SCHEMA: {{ .Values.snowflake.schema | quote }}
  DBT_TARGET: {{ .Values.snowflake.target | quote }}
{{- end }}
